/**
 * Display titles for grammar topics.
 *
 * UI text, not content: it labels the sourced explanation rather than
 * describing German. Generated from scripts/lib/grammar-map.ts, which is where
 * topic ids and their sources are defined.
 */
export const TOPIC_TITLES: Record<string, string> = {
  'alphabet-pronunciation': 'Alphabet and pronunciation',
  'personal-pronouns': 'Personal pronouns',
  'verb-sein-present': 'sein in the present tense',
  'present-regular': 'Present tense',
  'verb-haben-present': 'haben in the present tense',
  'w-questions': 'W-questions',
  'yes-no-questions': 'Yes/no questions',
  'noun-gender': 'Noun gender',
  'articles-definite-indefinite': 'Definite and indefinite articles',
  'plural-patterns': 'Plural patterns',
  'case-accusative': 'Accusative case',
  'kein': 'kein',
  'negation-nicht-vs-kein': 'nicht vs kein',
  'word-order-v2': 'Word order: the verb second',
  'word-order-inversion': 'Inversion',
  'verbs-stem-changing': 'Stem-changing verbs',
  'verbs-separable': 'Separable verbs',
  'modals-present': 'Modal verbs',
  'moechten': 'möchten',
  'possessive-articles': 'Possessive articles',
  'imperative': 'Imperative',
  'prepositions-time-basic': 'Prepositions of time',
  'prepositions-place-basic': 'Prepositions of place',
  'numbers': 'Numbers',
  'clock-time': 'Telling the time',
  'dates': 'Dates',
  'case-dative': 'Dative case',
  'dative-pronouns': 'Dative pronouns',
  'verbs-with-dative': 'Verbs with the dative',
  'perfekt-intro': 'Perfekt: an introduction',
  'perfekt-full': 'Perfekt',
  'praeteritum-sein-haben-modals': 'Präteritum of sein, haben and modals',
  'wechselpraepositionen': 'Two-way prepositions',
  'prepositions-dative': 'Dative prepositions',
  'prepositions-accusative': 'Accusative prepositions',
  'adjective-declension-strong': 'Strong adjective declension',
  'adjective-declension-weak': 'Weak adjective declension',
  'adjective-declension-mixed': 'Mixed adjective declension',
  'comparative': 'Comparative',
  'superlative': 'Superlative',
  'subordinate-clauses-basic': 'Subordinate clauses',
  'word-order-verb-final': 'Verb-final word order',
  'reflexive-verbs': 'Reflexive verbs',
  'verbs-with-prepositions': 'Verbs with prepositions',
  'da-wo-compounds': 'da- and wo- compounds',
  'konjunktiv2-present': 'Konjunktiv II',
  'indefinite-pronouns': 'Indefinite pronouns',
  'man': 'man',
  'zu-infinitive-intro': 'zu + infinitive',
  'praeteritum-full': 'Präteritum',
  'plusquamperfekt': 'Plusquamperfekt',
  'passive-present': 'Passive: present',
  'passive-praeteritum': 'Passive: Präteritum',
  'passive-perfekt': 'Passive: Perfekt',
  'passive-with-modals': 'Passive with modal verbs',
  'relative-clauses': 'Relative clauses',
  'relative-clauses-with-prepositions': 'Relative clauses with prepositions',
  'case-genitive': 'Genitive case',
  'prepositions-genitive': 'Genitive prepositions',
  'konjunktiv2-past': 'Konjunktiv II past',
  'als-ob': 'als ob',
  'subordinate-clauses-extended': 'Subordinate clauses, extended',
  'um-zu': 'um … zu',
  'two-part-conjunctions': 'Two-part conjunctions',
  'n-deklination': 'n-Deklination',
  'futur-1': 'Futur I',
  'infinitive-ohne-statt-zu': 'ohne … zu, statt … zu',
  'lassen': 'lassen',
  'b1-review': 'B1 review',
};
