import { expect, test } from '@playwright/test';

/**
 * Mobile smoke test (spec §6): a learner can start from nothing and answer a
 * question, which is the path that must never break.
 */
test('a new learner can start the course and answer a drill', async ({ page }) => {
  await page.goto('./');

  await expect(page.getByRole('heading', { name: 'Deutsch bis B1' })).toBeVisible();

  // Onboarding: one tap to a usable course.
  await page.getByRole('link', { name: /get started/i }).click();
  await page.getByRole('button', { name: /start from zero/i }).click();

  // Setting up builds the first unit's cards and only then redirects home;
  // waiting on the URL avoids racing that redirect.
  await page.waitForFunction(() => location.hash === '#/', null, { timeout: 25_000 });
  await expect(page.getByRole('link', { name: /^Unit 1 ·/ })).toBeVisible();

  // The course locks everything past unit 1.
  await page.goto('./#/course');
  await expect(page.locator('.unit-row').first()).toBeVisible();
  expect(await page.locator('.unit-row').count()).toBe(35);
  expect(await page.locator('.unit-row[aria-disabled="true"]').count()).toBe(34);

  // Unit 1 lists its topics collapsed — three full articles inline was a wall
  // of text — and expanding one reveals the sourced explanation and licence.
  await page.goto('./#/unit/1');
  await expect(page.getByRole('heading', { name: 'Alphabet, pronouns, sein' })).toBeVisible();
  const topic = page.locator('details.topic').first();
  await expect(topic.locator('.topic-body')).toBeHidden();
  await topic.locator('> summary').click();
  await expect(topic.locator('.topic-body')).toBeVisible();
  await expect(topic.locator('.source-note summary')).toContainText('CC-BY-SA');

  // A drill item accepts an answer and moves on.
  await page.goto('./#/unit/1/drill');
  await expect(page.locator('.prompt-text')).toBeVisible({ timeout: 15_000 });

  const choices = page.locator('button.choice, .gender-row button');
  if (await choices.count() > 0) {
    await choices.first().click();
  } else {
    await page.locator('input[type=text]').first().fill('test');
    await page.getByRole('button', { name: 'Check' }).click();
  }
  // Answering must produce a verdict and a way forward.
  await expect(page.locator('.verdict')).toBeVisible();
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.locator('.session-bar')).toContainText('2/');
});

test('a drill session hides the tab bar and collapses provenance', async ({ page }) => {
  await page.goto('./#/onboarding');
  await page.getByRole('button', { name: /start from zero/i }).click();
  await page.waitForFunction(() => location.hash === '#/', null, { timeout: 25_000 });

  // Outside a session the tab bar is the primary navigation.
  await expect(page.getByRole('navigation', { name: 'Primary' })).toBeVisible();

  await page.goto('./#/unit/1/drill');
  await expect(page.locator('.prompt-text')).toBeVisible({ timeout: 15_000 });

  // Inside one it is hidden: on a phone its height is worth more than the tabs.
  await expect(page.getByRole('navigation', { name: 'Primary' })).toBeHidden();
  await expect(page.locator('.session-bar')).toBeVisible();

  // Attribution stays on screen, but as one collapsed line rather than two.
  const note = page.locator('.source-note');
  await expect(note).toBeVisible();
  await expect(note.locator('summary')).toContainText('CC-BY');
  // The generator id is audit detail: present, but not on screen by default.
  await expect(note.locator('.source-note-body')).toBeHidden();
  await note.locator('summary').click();
  await expect(note.locator('.source-note-body')).toBeVisible();
  await expect(note.locator('.source-note-body')).toContainText('Generated by');
});

test('typing is not interrupted, and the umlaut keys insert', async ({ page }) => {
  await page.goto('./#/onboarding');
  await page.getByRole('button', { name: /start from zero/i }).click();
  await page.waitForFunction(() => location.hash === '#/', null, { timeout: 25_000 });
  await page.goto('./#/unit/1/drill');
  await expect(page.locator('.prompt-text')).toBeVisible({ timeout: 15_000 });

  // Find a typed item rather than a multiple-choice one.
  for (let i = 0; i < 8; i++) {
    if (await page.locator('input[type=text]').count() > 0) break;
    await page.locator('button.choice, .gender-row button').first().click();
    await page.getByRole('button', { name: 'Continue' }).click();
  }

  const input = page.locator('input[type=text]').first();
  await expect(input).toBeVisible();

  // Regression: the question object was rebuilt on every render, so a reset
  // effect cleared the field on each keystroke.
  await input.fill('Haus');
  await expect(input).toHaveValue('Haus');

  await page.getByRole('button', { name: 'ä', exact: true }).click();
  await expect(input).toHaveValue('Hausä');
});

test('deep links and the attributions page survive a reload', async ({ page }) => {
  await page.goto('./#/attributions');
  await expect(page.getByRole('heading', { name: 'Tatoeba Project' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Attributions' })).toBeVisible();

  await page.goto('./#/no-such-route');
  await expect(page.getByRole('heading', { name: 'Page not found' })).toBeVisible();
});
