import { expect, test, type Page } from '@playwright/test';

/**
 * Mobile smoke test (spec §6): a learner can start from nothing and answer a
 * question, which is the path that must never break.
 */
/**
 * A drill presents each of the unit's new words before it asks anything, so a
 * test that wants a question has to walk past the presentation cards first.
 */
async function pastPresentations(page: Page): Promise<void> {
  const gotIt = page.getByRole('button', { name: 'Got it' });
  for (let i = 0; i < 40 && (await gotIt.count()) > 0; i += 1) {
    await gotIt.click();
    await page.waitForTimeout(60);
  }
}

test('a new learner can start the course and answer a drill', async ({ page }) => {
  await page.goto('./');

  await expect(page.getByRole('heading', { name: 'Deutsch bis B1' })).toBeVisible();

  // Onboarding: one tap to a usable course.
  await page.getByRole('link', { name: /get started/i }).click();
  await page.getByRole('button', { name: /start from zero/i }).click();

  // Setting up builds the first unit's cards and only then redirects home;
  // waiting on the URL avoids racing that redirect.
  await page.waitForFunction(() => location.hash === '#/', null, { timeout: 25_000 });
  await expect(page.getByRole('link', { name: /^Unit 1 ·/ })).toBeVisible();

  // The course locks everything past unit 1. Counted over unit rows only —
  // the list also carries a level test after the last unit of each level.
  await page.goto('./#/course');
  await expect(page.locator('.unit-row').first()).toBeVisible();
  const unitRows = page.locator('.unit-row').filter({ hasNotText: 'level test' });
  expect(await unitRows.count()).toBe(35);
  expect(await unitRows.and(page.locator('[aria-disabled="true"]')).count()).toBe(34);

  // Unit 1 lists its topics collapsed — three full articles inline was a wall
  // of text — and expanding one reveals the sourced explanation and licence.
  await page.goto('./#/unit/1');
  await expect(page.getByRole('heading', { name: 'Alphabet, pronouns, sein' })).toBeVisible();
  const topic = page.locator('details.topic').first();
  await expect(topic.locator('.topic-body')).toBeHidden();
  await topic.locator('> summary').click();
  await expect(topic.locator('.topic-body')).toBeVisible();
  await expect(topic.locator('.source-note summary')).toContainText('CC-BY-SA');

  // A drill item accepts an answer and moves on.
  await page.goto('./#/unit/1/drill');
  await expect(page.locator('.meet-word, .prompt-text').first()).toBeVisible({ timeout: 15_000 });
  await pastPresentations(page);
  await expect(page.locator('.prompt-text')).toBeVisible();

  const choices = page.locator('button.choice, .gender-row button');
  if (await choices.count() > 0) {
    await choices.first().click();
  } else {
    await page.locator('input[type=text]').first().fill('test');
    await page.getByRole('button', { name: 'Check' }).click();
  }
  // Answering must produce a verdict and a way forward.
  await expect(page.locator('.verdict')).toBeVisible();
  const before = await page.locator('.session-bar').innerText();
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.locator('.session-bar')).not.toHaveText(before);
});

test('a drill session hides the tab bar and collapses provenance', async ({ page }) => {
  await page.goto('./#/onboarding');
  await page.getByRole('button', { name: /start from zero/i }).click();
  await page.waitForFunction(() => location.hash === '#/', null, { timeout: 25_000 });

  // Outside a session the tab bar is the primary navigation.
  await expect(page.getByRole('navigation', { name: 'Primary' })).toBeVisible();

  await page.goto('./#/unit/1/drill');
  await expect(page.locator('.meet-word, .prompt-text').first()).toBeVisible({ timeout: 15_000 });

  // Inside one it is hidden: on a phone its height is worth more than the tabs.
  await expect(page.getByRole('navigation', { name: 'Primary' })).toBeHidden();
  await expect(page.locator('.session-bar')).toBeVisible();

  // Attribution stays on screen, but as one collapsed line rather than two.
  const note = page.locator('.source-note');
  await expect(note).toBeVisible();
  await expect(note.locator('summary')).toContainText('CC-BY');
  // The generator id is audit detail: present, but not on screen by default.
  await expect(note.locator('.source-note-body')).toBeHidden();
  await note.locator('summary').click();
  await expect(note.locator('.source-note-body')).toBeVisible();
  await expect(note.locator('.source-note-body')).toContainText('Generated by');
});

test('typing is not interrupted, and the umlaut keys insert', async ({ page }) => {
  await page.goto('./#/onboarding');
  await page.getByRole('button', { name: /start from zero/i }).click();
  await page.waitForFunction(() => location.hash === '#/', null, { timeout: 25_000 });
  await page.goto('./#/unit/1/drill');
  await expect(page.locator('.meet-word, .prompt-text').first()).toBeVisible({ timeout: 15_000 });
  await pastPresentations(page);

  // Find a typed item. Practice is a ladder, so recognition comes first and a
  // typed card is a little way in.
  for (let i = 0; i < 25; i++) {
    if (await page.locator('input[type=text]').count() > 0) break;
    await page.locator('button.choice, .gender-row button').first().click();
    await page.getByRole('button', { name: 'Continue' }).click();
  }

  const input = page.locator('input[type=text]').first();
  await expect(input).toBeVisible();

  // Regression: the question object was rebuilt on every render, so a reset
  // effect cleared the field on each keystroke.
  await input.fill('Haus');
  await expect(input).toHaveValue('Haus');

  await page.getByRole('button', { name: 'ä', exact: true }).click();
  await expect(input).toHaveValue('Hausä');
});

test('deep links and the attributions page survive a reload', async ({ page }) => {
  await page.goto('./#/attributions');
  await expect(page.getByRole('heading', { name: 'Tatoeba Project' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Attributions' })).toBeVisible();

  await page.goto('./#/no-such-route');
  await expect(page.getByRole('heading', { name: 'Page not found' })).toBeVisible();
});

test('the daily test runs and is reachable from home', async ({ page }) => {
  await page.goto('./#/onboarding');
  await page.getByRole('button', { name: /start from zero/i }).click();
  await page.waitForFunction(() => location.hash === '#/', null, { timeout: 25_000 });

  await page.locator('a[href="#/test/daily"]').click();
  await expect(page.locator('.prompt-text')).toBeVisible({ timeout: 20_000 });
  // 10 items, and strict test mode rather than practice.
  await expect(page.locator('.session-bar')).toContainText('Test 1/10');
});

test('a level test draws 60 items across the level', async ({ page }) => {
  await page.goto('./#/onboarding');
  await page.getByRole('button', { name: /start from zero/i }).click();
  await page.waitForFunction(() => location.hash === '#/', null, { timeout: 25_000 });

  await page.goto('./#/test/level/A1');
  await expect(page.locator('.prompt-text')).toBeVisible({ timeout: 20_000 });
  await expect(page.locator('.session-bar')).toContainText('Test 1/60');
});

test('the course lists a level test after the last unit of each level', async ({ page }) => {
  await page.goto('./#/course');
  await expect(page.locator('.unit-row').first()).toBeVisible();
  // 35 units plus one level test each for A1, A2 and B1.
  expect(await page.locator('.unit-row').count()).toBe(38);
  await expect(page.locator('.unit-row', { hasText: 'A1 level test' })).toBeVisible();
});

test('placement runs a round and places the learner', async ({ page }) => {
  await page.goto('./#/onboarding');
  await page.locator('a[href="#/placement"]').click();
  await expect(page.locator('.prompt-text')).toBeVisible({ timeout: 20_000 });
  await expect(page.locator('.session-bar')).toContainText('A1 1/10');

  // Answer everything wrong: the round fails, so placement stops at A1.
  for (let i = 0; i < 12; i++) {
    if (await page.getByRole('heading', { name: 'Placement complete' }).count() > 0) break;
    const choices = page.locator('button.choice, .gender-row button');
    if (await choices.count() > 0) {
      await choices.last().click();
    } else {
      const inputs = page.locator('input[type=text]');
      const n = await inputs.count();
      if (n === 0) break;
      for (let k = 0; k < n; k++) await inputs.nth(k).fill('zzz');
      await page.getByRole('button', { name: 'Check' }).click();
    }
    const cont = page.getByRole('button', { name: 'Continue' });
    if (await cont.count() === 0) break;
    await cont.click();
  }

  await expect(page.getByRole('heading', { name: 'Placement complete' })).toBeVisible();
  await page.getByRole('button', { name: /start here/i }).click();
  await page.waitForFunction(() => location.hash === '#/', null, { timeout: 25_000 });
  await expect(page.getByRole('link', { name: /^Unit 1 ·/ })).toBeVisible();
});

test('a sentence can be broken down word by word after answering', async ({ page }) => {
  await page.goto('./#/onboarding');
  await page.getByRole('button', { name: /start from zero/i }).click();
  await page.waitForFunction(() => location.hash === '#/', null, { timeout: 25_000 });

  await page.goto('./#/unit/1/drill');
  await expect(page.locator('.meet-word, .prompt-text').first()).toBeVisible({ timeout: 15_000 });
  await pastPresentations(page);

  // Work through the session until a sentence item comes up; only those can be
  // broken down, and the order is seeded rather than fixed.
  const breakDown = page.getByRole('button', { name: 'Break it down' });
  for (let i = 0; i < 30 && (await breakDown.count()) === 0; i += 1) {
    const choices = page.locator('button.choice, .gender-row button');
    if ((await choices.count()) > 0) {
      await choices.first().click();
    } else {
      await page.locator('input[type=text]').first().fill('x');
      await page.getByRole('button', { name: 'Check' }).click();
    }
    await expect(page.locator('.verdict')).toBeVisible();
    if ((await breakDown.count()) > 0) break;
    await page.getByRole('button', { name: 'Continue' }).click();
    await expect(page.locator('.prompt-text')).toBeVisible();
  }
  expect(await breakDown.count()).toBe(1);

  await breakDown.click();
  const rows = page.locator('.breakdown-list li');
  await expect(rows.first()).toBeVisible();
  expect(await rows.count()).toBeGreaterThan(2);
  // The translation and at least one word's meaning have to be readable.
  await expect(page.locator('.breakdown-en')).not.toBeEmpty();
  await expect(rows.first().locator('.breakdown-word')).not.toBeEmpty();
  await expect(page.locator('.breakdown-meaning').first()).not.toBeEmpty();
  // The form tables arrive after the meanings; at least one word is labelled.
  await expect(page.locator('.breakdown-role').first()).toBeVisible({ timeout: 15_000 });
});

test('a drill presents each new word before asking about it', async ({ page }) => {
  await page.goto('./#/onboarding');
  await page.getByRole('button', { name: /start from zero/i }).click();
  await page.waitForFunction(() => location.hash === '#/', null, { timeout: 25_000 });

  await page.goto('./#/unit/1/drill');
  // Regression: a unit used to open with "write this in German" for a word the
  // learner had never seen.
  await expect(page.locator('.meet-word')).toBeVisible({ timeout: 15_000 });
  await expect(page.locator('.meet-meaning')).not.toBeEmpty();
  // A presentation card asks nothing, so there is no way to answer it wrong.
  expect(await page.locator('input[type=text]').count()).toBe(0);
  expect(await page.locator('button.choice').count()).toBe(0);

  await page.getByRole('button', { name: 'Got it' }).click();
  await expect(page.locator('.session-bar')).toContainText('2/');
});

test('the whole course works with the network off', async ({ page, context }) => {
  // Regression: the service worker's data route was serialised into sw.js
  // still referring to a build-time constant, so it threw on every request,
  // matched nothing, and cached no course data at all. The app said it was
  // ready to work offline and then had nothing offline.
  await page.goto('./');
  await page.getByRole('link', { name: /get started/i }).click();
  await page.getByRole('button', { name: /start from zero/i }).click();
  await page.waitForFunction(() => location.hash === '#/', null, { timeout: 25_000 });

  // The course is downloaded deliberately, not only when a screen is visited.
  // Settings reports what is actually cached, and keeps looking while the
  // download runs, so this waits on the app's own accounting rather than on a
  // count of cache entries.
  await page.goto('./#/settings');
  await expect(page.getByText(/The whole course is on this device/)).toBeVisible({
    timeout: 120_000,
  });

  await context.setOffline(true);
  // Navigating away aborts whatever is in flight, and an abort is reported as
  // a failed request too; only a real network error counts here.
  const failures: string[] = [];
  page.on('requestfailed', (r) => {
    const why = r.failure()?.errorText ?? '';
    if (!why.includes('ABORTED')) failures.push(`${new URL(r.url()).pathname} (${why})`);
  });

  // A unit the learner never opened while online.
  await page.goto('./#/unit/3');
  await expect(page.getByRole('heading', { name: /Nouns/ })).toBeVisible({ timeout: 15_000 });

  await page.goto('./#/unit/3/drill');
  await expect(page.locator('.meet-word, .prompt-text').first()).toBeVisible({ timeout: 15_000 });

  await page.goto('./#/dictionary');
  await expect(page.locator('.dict-row, .card').first()).toBeVisible({ timeout: 15_000 });

  expect(failures).toEqual([]);
  await context.setOffline(false);
});
