/**
 * Provenance for one item, as a single small line that expands on tap.
 *
 * The spec requires the source and licence to be visible under every piece of
 * German, but on a phone two lines of attribution under every card crowds out
 * the thing being studied. The summary keeps the attribution visible; the
 * link and the generator id — audit detail, not study material — sit behind
 * the toggle.
 */
export function SourceNote({
  source,
  license,
  url,
  generator,
}: {
  source: string;
  license: string;
  url?: string;
  /** Id of the deterministic rule that produced the item. */
  generator?: string;
}) {
  return (
    <details class="source-note">
      <summary>
        {source} · {license}
      </summary>
      <div class="source-note-body">
        {url ? (
          <a href={url} target="_blank" rel="noopener noreferrer">Open the source</a>
        ) : null}
        {generator ? <div class="mono">Generated by: {generator}</div> : null}
      </div>
    </details>
  );
}
